linters:
  PropertySortOrder:
    enabled: true
    order: smacss
    ignore_unspecified: false
    min_properties: 2
    separate_groups: false
  ColorKeyword:
    enabled: false
  ColorVariable:
    enabled: false
  SelectorFormat:
    enabled: true
    convention: hyphenated_BEM
